apiVersion: v1
kind: Secret
metadata:
  name: nexora-backend-secret
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://postgres:5432/nexora
  DB_USERNAME: nexora
  DB_PASSWORD: nexora123
  JWT_SECRET: super-secret-key-change-me
  MAIL_USERNAME: your-email@gmail.com
  MAIL_PASSWORD: your-app-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nexora-backend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nexora-backend-secret
          ports:
            - containerPort: 8081
